### ISSUE TITLE
Import fails on MyTracks file

### ISSUE THREAD

**Issue by johnjohndoe** [ptrv/GpxDBImporterExporter#2]
I tried to import a GPX file produced by [MyTracks](https://code.google.com/p/mytracks/). Here is what I did.
1. Start the program (compiled from the latest sources)
2. Create a new database
3. Enter a user name
4. Select a single GPX file
5. Press import

Here is what the console outputs.

---

Database error: nothing to read
Database error: nothing to read
Database error: nothing to read
Database error: nothing to read
Database error: SQL logic error or missing database 
query: INSERT INTO gpsdata (gpsdataid,latitude,longitude,elevation,time,segment,user,file,location) VALUES ("752","52.5062714","13.4820404","73","2012-01-05T21:24:31Z","1","1","0","2");
Database error: SQL logic error or missing database 
query: INSERT INTO gpsdata (gpsdataid,latitude,longitude,elevation,time,segment,user,file,location) VALUES ("870","52.5132904","13.4768496","79","2012-01-05T21:28:14Z","1","1","0","2");
Database error: SQL logic error or missing database 
query: INSERT INTO gpsdata (gpsdataid,latitude,longitude,elevation,time,segment,user,file,location) VALUES ("917","52.5158195","13.4784698","80","2012-01-05T21:30:45Z","1","1","0","2");
Database error: SQL logic error or missing database 
query: INSERT INTO gpsdata (gpsdataid,latitude,longitude,elevation,time,segment,user,file,location) VALUES ("935","52.5188217","13.4786396","0","2012-01-05T21:32:20Z","2","1","0","2");
...

---

I uploaded the GPX file [here](http://pastebin.com/y8eAPtvz).

**Comment by ptrv** [comment]
Which version? DEBUG or RELEASE build?
Are none of the GPX points imported or not all?

**Comment by ptrv** [comment]
please build a Release version: 
`make CONFIG=Release`
What is the output then?

**Comment by johnjohndoe** [comment]
Looks good. You should probably set the default make config to release. Further, I suggest that you add this option to the README or add an additional INSTALL file.

**Comment by ptrv** [comment]
Good point with the README and thanks for reporting.

Actually the gps points which you get an INSERT error with are duplicates (same lat, lon, user and time and set as unique) and is normal. sqlite feedback is not the best. 

You can verify the duplicate entry in your GPX file you pasted in pastebin. Also have to do something about the output text.

**Comment by johnjohndoe** [comment]
Might be a interpolation setting done by MyTracks that copies the gps points.

**Comment by ptrv** [comment]
It is good that default make CONFIG is Debug. I will put a note into the README. I use Debug all the time and Release just for a binary release.
