### ISSUE TITLE
Database error: nothing to read

### ISSUE THREAD

**Issue by johnjohndoe** [ptrv/GpxDBImporterExporter#3]
While importing a GPX file produced by [Open GPS Tracker](http://code.google.com/p/open-gpstracker/) the following error message appears in the console: _Database error: nothing to read_. Here is what I did.
1. Start the program (compiled from the latest sources)
2. Create a new database
3. Enter a user name
4. Select a single GPX file
5. Press import

I uploaded the file [here](http://pastebin.com/YXGijYg7).

**Comment by ptrv** [comment]
see [#2](https://github.com/ptrv/GpxDBImporterExporter/issues/2#issuecomment-5158885)

**Comment by johnjohndoe** [comment]
see #2
